#!/usr/bin/env bash
# Sourced (not executed) by every other scripts/*.sh. Derives a stable per-worktree identity
# -- ports and a database name -- so N worktrees can run their own full local stack at the
# same time with zero collision. The primary `main` checkout keeps the historical defaults
# (backend :8080, frontend :3000, database `worktrac`) so existing muscle memory and any
# external bookmarks/scripts pointing at those ports keep working unchanged.
#
# Usage: `source "$(dirname "${BASH_SOURCE[0]}")/worktree-env.sh"` from another script in
# this directory. Exports: WORKTREE_SLUG, BACKEND_PORT, FRONTEND_PORT, DB_NAME,
# SPRING_DATASOURCE_URL, CORS_ALLOWED_ORIGINS, VITE_BACKEND_ORIGIN, APP_EMAIL_APP_URL.
set -euo pipefail

_WTENV_REPO_ROOT="$(git rev-parse --show-toplevel)"
_WTENV_BRANCH="$(git -C "$_WTENV_REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
if [ -z "$_WTENV_BRANCH" ] || [ "$_WTENV_BRANCH" = "HEAD" ]; then
  # Detached HEAD (rare) -- fall back to the directory name so this is still stable/repeatable.
  _WTENV_BRANCH="$(basename "$_WTENV_REPO_ROOT")"
fi

_wtenv_slugify() {
  echo -n "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g; s/^_+|_+$//g' | cut -c1-30
}

_WTENV_FILE="$_WTENV_REPO_ROOT/.env.worktree"

if [ "$_WTENV_BRANCH" = "main" ]; then
  WORKTREE_SLUG="main"
  BACKEND_PORT=8080
  FRONTEND_PORT=3000
  DB_NAME="worktrac"
else
  WORKTREE_SLUG="$(_wtenv_slugify "$_WTENV_BRANCH")"
  BACKEND_PORT=""
  FRONTEND_PORT=""
  if [ -f "$_WTENV_FILE" ]; then
    # shellcheck disable=SC1090
    source "$_WTENV_FILE"
  fi
  if [ -z "${BACKEND_PORT:-}" ] || [ -z "${FRONTEND_PORT:-}" ]; then
    _wtenv_port_free() {
      # True (0) if nothing is currently LISTENING on port $1.
      ! netstat -ano 2>/dev/null | grep -qE ":$1[[:space:]].*LISTENING"
    }
    BACKEND_PORT=8081
    while ! _wtenv_port_free "$BACKEND_PORT"; do BACKEND_PORT=$((BACKEND_PORT + 1)); done
    FRONTEND_PORT=3001
    while ! _wtenv_port_free "$FRONTEND_PORT"; do FRONTEND_PORT=$((FRONTEND_PORT + 1)); done
    {
      echo "# Auto-generated by scripts/worktree-env.sh for worktree branch '$_WTENV_BRANCH'."
      echo "# Safe to delete -- ports will be reallocated (possibly differently) on the next run."
      echo "WORKTREE_SLUG=$WORKTREE_SLUG"
      echo "BACKEND_PORT=$BACKEND_PORT"
      echo "FRONTEND_PORT=$FRONTEND_PORT"
    } > "$_WTENV_FILE"
  fi
  DB_NAME="worktrac_${WORKTREE_SLUG}"
fi

export WORKTREE_SLUG BACKEND_PORT FRONTEND_PORT DB_NAME
export SPRING_DATASOURCE_URL="jdbc:sqlserver://localhost:1434;database=${DB_NAME};encrypt=false;trustServerCertificate=true"
export CORS_ALLOWED_ORIGINS="http://localhost:${FRONTEND_PORT}"
export VITE_BACKEND_ORIGIN="http://localhost:${BACKEND_PORT}"
export APP_EMAIL_APP_URL="http://localhost:${FRONTEND_PORT}/app/log"
