#!/usr/bin/env bash
# Sourced (not executed) by every other scripts/*.sh. Derives a stable per-worktree identity
# -- ports and a database name -- so N worktrees can run their own full local stack at the
# same time with zero collision. The primary `main` checkout keeps the historical defaults
# (backend :8080, frontend :3000, database `worktrac`) so existing muscle memory and any
# external bookmarks/scripts pointing at those ports keep working unchanged.
#
# Usage: `source "$(dirname "${BASH_SOURCE[0]}")/worktree-env.sh"` from another script in
# this directory. Exports: WORKTREE_SLUG, BACKEND_PORT, FRONTEND_PORT, DB_NAME,
# SPRING_DATASOURCE_URL, CORS_ALLOWED_ORIGINS, VITE_BACKEND_ORIGIN, APP_EMAIL_APP_URL.
set -euo pipefail

_WTENV_REPO_ROOT="$(git rev-parse --show-toplevel)"
_WTENV_BRANCH="$(git -C "$_WTENV_REPO_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
if [ -z "$_WTENV_BRANCH" ] || [ "$_WTENV_BRANCH" = "HEAD" ]; then
  # Detached HEAD (rare) -- fall back to the directory name so this is still stable/repeatable.
  _WTENV_BRANCH="$(basename "$_WTENV_REPO_ROOT")"
fi

_wtenv_slugify() {
  echo -n "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g; s/^_+|_+$//g' | cut -c1-30
}

_WTENV_FILE="$_WTENV_REPO_ROOT/.env.worktree"

if [ "$_WTENV_BRANCH" = "main" ]; then
  WORKTREE_SLUG="main"
  BACKEND_PORT=8080
  FRONTEND_PORT=3000
  DB_NAME="worktrac"
else
  WORKTREE_SLUG="$(_wtenv_slugify "$_WTENV_BRANCH")"
  BACKEND_PORT=""
  FRONTEND_PORT=""
  if [ -f "$_WTENV_FILE" ]; then
    # shellcheck disable=SC1090
    source "$_WTENV_FILE"
  fi
  # Ports every OTHER worktree has already written into its own .env.worktree. A port with
  # nothing LISTENING on it is NOT free if a sibling has it cached -- that sibling's stack is
  # merely stopped right now, and both up.sh and down.sh act by port, so sharing one means each
  # worktree silently tears the other's stack down. That is exactly what happened: three
  # worktrees all allocated 8081/3001 because each probed while the others were stopped, and
  # from then on every up.sh/down.sh killed a concurrent session's dev servers mid-run --
  # which looked for all the world like the Vite dev server crashing on its own.
  _wtenv_sibling_claims() {
    local self me f
    self="$(basename "$_WTENV_REPO_ROOT")"
    for f in "$_WTENV_REPO_ROOT"/../*/.env.worktree; do
      [ -f "$f" ] || continue
      me="$(basename "$(dirname "$f")")"
      [ "$me" = "$self" ] && continue
      sed -nE 's/^(BACKEND|FRONTEND)_PORT=([0-9]+)$/\2/p' "$f"
    done
  }
  _WTENV_CLAIMED="$(_wtenv_sibling_claims || true)"

  _wtenv_port_taken() {
    # The primary `main` checkout's fixed ports are never up for grabs, even while it's stopped.
    if [ "$1" = "8080" ] || [ "$1" = "3000" ]; then return 0; fi
    if netstat -ano 2>/dev/null | grep -qE ":$1[[:space:]].*LISTENING"; then return 0; fi
    if printf '%s\n' "$_WTENV_CLAIMED" | grep -qx "$1"; then return 0; fi
    return 1
  }

  # A pre-existing collision is only WARNED about, never auto-resolved. Reallocating here would
  # have to pick a loser, and any rule for that can move a worktree whose stack is running right
  # now out from under it. Deleting the offending .env.worktree (the file says it's safe to) and
  # re-running is the deliberate, human-timed fix.
  if [ -n "${BACKEND_PORT:-}" ] && [ -n "${FRONTEND_PORT:-}" ] \
     && printf '%s\n' "$_WTENV_CLAIMED" | grep -qxE "$BACKEND_PORT|$FRONTEND_PORT"; then
    echo "worktree-env: WARNING -- :$BACKEND_PORT/:$FRONTEND_PORT are also claimed by another" \
         "worktree. up.sh/down.sh act by port, so these two worktrees will kill each other's" \
         "stacks. Delete this worktree's .env.worktree and re-run to move onto free ports." >&2
  fi

  if [ -z "${BACKEND_PORT:-}" ] || [ -z "${FRONTEND_PORT:-}" ]; then
    BACKEND_PORT=8081
    while _wtenv_port_taken "$BACKEND_PORT"; do BACKEND_PORT=$((BACKEND_PORT + 1)); done
    FRONTEND_PORT=3001
    while _wtenv_port_taken "$FRONTEND_PORT"; do FRONTEND_PORT=$((FRONTEND_PORT + 1)); done
    {
      echo "# Auto-generated by scripts/worktree-env.sh for worktree branch '$_WTENV_BRANCH'."
      echo "# Safe to delete -- ports will be reallocated (possibly differently) on the next run."
      echo "WORKTREE_SLUG=$WORKTREE_SLUG"
      echo "BACKEND_PORT=$BACKEND_PORT"
      echo "FRONTEND_PORT=$FRONTEND_PORT"
    } > "$_WTENV_FILE"
  fi
  DB_NAME="worktrac_${WORKTREE_SLUG}"
fi

export WORKTREE_SLUG BACKEND_PORT FRONTEND_PORT DB_NAME
export SPRING_DATASOURCE_URL="jdbc:sqlserver://localhost:1434;database=${DB_NAME};encrypt=false;trustServerCertificate=true"
export CORS_ALLOWED_ORIGINS="http://localhost:${FRONTEND_PORT}"
export VITE_BACKEND_ORIGIN="http://localhost:${BACKEND_PORT}"
export APP_EMAIL_APP_URL="http://localhost:${FRONTEND_PORT}/app/log"
