import { comparableLb, comparableValue, epley, lbE7 } from './formulas';
import { setVolumeScaled, volumeKindOf, volumeScale } from './sessionVolume';

// The PRs board and Trends, derived from the History the device already holds instead of asking
// StatsService to load every set the person has logged (docs/architecture/prs-trends-from-history.md).
//
// Each function returns EXACTLY the shape its endpoint returns -- PrRowDto[], TrendsOverviewDto,
// ExerciseTrendPointDto[], ExerciseRecordsDto -- so the screens need not change to read it, and
// shared/record-rules/stats-from-history-cases.json (generated by the backend's
// StatsFromHistoryCasesTest from the real endpoints) can compare the two field for field.
//
// Two rules make the answers equal rather than close:
//
//  - EXACT arithmetic. Pounds are summed as integers x 1e7 (formulas.js#lbE7, sessionVolume.js) and
//    rounded half-up to 0.1 ONCE, the way the server's BigDecimal does. Comparisons can use the
//    measure functions' doubles: each is the nearest double to an exact decimal, so they order and
//    tie exactly as the decimals do.
//  - ONE TIE RULE, the server's too. When two sets tie for a record, the heavier load holds it (or
//    the record's own second measure -- more reps for top weight, a longer hold for heaviest load
//    held); a full tie goes to the earlier workout. Sets are walked in History's order reversed --
//    workout start, then id, then each set as logged -- so "the first one wins" IS "the earlier
//    workout". A session total has no one load, so it goes straight to the earlier workout.
//
// The measures themselves (est. 1RM, top weight, what a set ranks by, volume) are formulas.js's and
// sessionVolume.js's; nothing here re-derives them.

const E7 = 1e7;
const DAY_MS = 86400000;
const MAX_WEEKS = 260;
const HEATMAP_DAYS = 182;
const MAX_PR_BREAKDOWN_RUNS = 10;

// A double that is the nearest double to a decimal of at most seven places, back to that decimal x 1e7.
const toE7 = (x) => Math.round(Number(x) * E7);

// n / scale, rounded half-up to one decimal (BigDecimal#setScale(1, HALF_UP) for positive values).
// BigInt because five years of pounds x 1e7 x 20 passes 2^53.
function tenths(n, scale) {
  const t = (BigInt(n) * 20n + BigInt(scale)) / (2n * BigInt(scale));
  return Number(t) / 10;
}

const isHold = (set) => set?.durationSeconds != null;
const weightLbE7 = (set) => lbE7(Number(set.weight) || 0, set.unit || 'lb');
const loadVolumeE7 = (set) => setVolumeScaled(set, 'load');

// "Is (value, tiebreak) a better record than the incumbent?" -- StatsService#isBetter.
const isBetter = (value, tiebreak, bestValue, bestTiebreak) =>
  value > bestValue || (value === bestValue && tiebreak > bestTiebreak);

// History is newest first (startedAt, then id, descending); reversed, it is the order records
// resolve in. Each set carries its workout.
function setsInOrder(history, exerciseId) {
  const out = [];
  for (let i = (history?.length ?? 0) - 1; i >= 0; i -= 1) {
    const session = history[i];
    for (const entry of session.entries || []) {
      if (exerciseId != null && entry.exerciseId !== exerciseId) continue;
      for (const set of entry.sets || []) out.push({ set, session, entry });
    }
  }
  return out;
}

// ── dates in the viewer's zone ────────────────────────────────────────────────────────────────

const formatters = new Map();

function formatterFor(zone) {
  if (!formatters.has(zone)) {
    let formatter;
    try {
      formatter = new Intl.DateTimeFormat('en-CA', { timeZone: zone, year: 'numeric', month: '2-digit', day: '2-digit' });
    } catch {
      // StatsService#resolveZone: an unrecognized zone is UTC rather than a failure.
      formatter = new Intl.DateTimeFormat('en-CA', { timeZone: 'UTC', year: 'numeric', month: '2-digit', day: '2-digit' });
    }
    formatters.set(zone, formatter);
  }
  return formatters.get(zone);
}

// Days since the epoch of the calendar date `instant` falls on in `zone`.
function localDay(instant, zone) {
  const parts = Object.fromEntries(formatterFor(zone).formatToParts(new Date(instant)).map((p) => [p.type, p.value]));
  return Date.UTC(Number(parts.year), Number(parts.month) - 1, Number(parts.day)) / DAY_MS;
}

const isoDay = (day) => new Date(day * DAY_MS).toISOString().slice(0, 10);
const mondayOf = (day) => day - ((new Date(day * DAY_MS).getUTCDay() + 6) % 7);

// ── the PRs board: GET /prs ───────────────────────────────────────────────────────────────────

// THE tie rule for a record that names one set (StatsService#bestSet): the higher value, then the
// heavier load, then the earlier set -- items arrive chronologically, so the first wins a full tie.
function bestSet(items) {
  let best = null;
  let bestValue = null;
  for (const item of items) {
    const value = comparableValue(item.set);
    if (bestValue == null || isBetter(value, weightLbE7(item.set), bestValue, weightLbE7(best.set))) {
      bestValue = value;
      best = item;
    }
  }
  return best;
}

function bestDto({ set, session }) {
  return {
    weight: Number(set.weight),
    reps: set.reps,
    durationSeconds: set.durationSeconds ?? null,
    unit: set.unit,
    est1rm: isHold(set) ? null : epley(set.weight, set.reps),
    sessionStartedAt: session.startedAt,
  };
}

// The work behind a session-level record: consecutive identical sets collapsed into runs, capped.
function breakdown(items) {
  const runs = [];
  for (const { set } of items) {
    const weightLb = tenths(weightLbE7(set), E7);
    const durationSeconds = set.durationSeconds ?? null;
    const last = runs[runs.length - 1];
    if (last && last.weightLb === weightLb && last.reps === set.reps && last.durationSeconds === durationSeconds) {
      last.count += 1;
    } else if (runs.length < MAX_PR_BREAKDOWN_RUNS) {
      runs.push({ weightLb, reps: set.reps, durationSeconds, count: 1 });
    }
  }
  return runs;
}

const setMeasure = (valueScaled, scale, { set, session }) => ({
  value: tenths(valueScaled, scale),
  weightLb: tenths(weightLbE7(set), E7),
  reps: set.reps,
  sessionStartedAt: session.startedAt,
  sets: [],
  setCount: 0,
});

// The session with the largest total (the first, on a tie), naming its work.
function sessionMeasure(totals, value) {
  let best = null;
  for (const s of totals.values()) if (best == null || s.total > best.total) best = s;
  return {
    value: value(best.total),
    weightLb: null,
    reps: null,
    sessionStartedAt: best.session.startedAt,
    sets: breakdown(best.items),
    setCount: best.items.length,
  };
}

function prRow(exerciseId, exerciseName, items) {
  const durationTracked = items.some(({ set }) => isHold(set));
  const bodyweightOnly = items.every(({ set }) => Number(set.weight) === 0);
  const kind = volumeKindOf(items.map(({ set }) => set));
  let heaviest = null;
  let bestSetVolume = null;
  const volume = new Map();
  const reps = new Map();
  for (const item of items) {
    const { set, session } = item;
    if (heaviest == null || isBetter(weightLbE7(set), set.reps, weightLbE7(heaviest.set), heaviest.set.reps)) heaviest = item;
    if (bestSetVolume == null || isBetter(loadVolumeE7(set), weightLbE7(set), loadVolumeE7(bestSetVolume.set), weightLbE7(bestSetVolume.set))) {
      bestSetVolume = item;
    }
    for (const [totals, add] of [[volume, setVolumeScaled(set, kind)], [reps, set.reps]]) {
      if (!totals.has(session.id)) totals.set(session.id, { session, total: 0, items: [] });
      const s = totals.get(session.id);
      s.total += add;
      s.items.push(item);
    }
  }
  const noVolumeMeasure = bodyweightOnly || durationTracked;
  return {
    exerciseId,
    exerciseName,
    best: bestDto(bestSet(items)),
    measures: {
      heaviest: bodyweightOnly ? null : setMeasure(weightLbE7(heaviest.set), E7, heaviest),
      sessionVolume: sessionMeasure(volume, (total) => tenths(total, volumeScale(kind))),
      bestSetVolume: noVolumeMeasure ? null : setMeasure(loadVolumeE7(bestSetVolume.set), E7, bestSetVolume),
      totalReps: durationTracked ? null : sessionMeasure(reps, (total) => total),
    },
    bodyweightOnly,
    durationTracked,
    volumeKind: kind,
  };
}

// String.CASE_INSENSITIVE_ORDER, as StatsService sorts the board.
const byNameIgnoringCase = (a, b) => {
  const x = a.exerciseName.toLowerCase();
  const y = b.exerciseName.toLowerCase();
  return x < y ? -1 : x > y ? 1 : 0;
};

export function prBoard(history) {
  const byExercise = new Map();
  for (const item of setsInOrder(history)) {
    const id = item.entry.exerciseId;
    if (!byExercise.has(id)) byExercise.set(id, { name: item.entry.exerciseName, items: [] });
    byExercise.get(id).items.push(item);
  }
  return [...byExercise].map(([id, { name, items }]) => prRow(id, name, items)).sort(byNameIgnoringCase);
}

// ── Trends overview: GET /trends/overview ─────────────────────────────────────────────────────

// `hiddenSessions` is the History window's count of workouts behind the Free floor: the overview's
// hasAnyHistory is all-time, so History behind the window still means this person has trained.
export function trendsOverview(history, { weeks, zone, now, hiddenSessions = 0 }) {
  const effectiveWeeks = Math.min(Math.max(weeks, 1), MAX_WEEKS);
  const today = localDay(now, zone);
  const currentWeek = mondayOf(today);
  const rangeStart = currentWeek - 7 * (effectiveWeeks - 1);

  const sessions = new Map();
  for (const { set, session } of setsInOrder(history)) {
    if (!sessions.has(session.id)) {
      sessions.set(session.id, { day: localDay(session.startedAt, zone), volume: 0, sets: 0, reps: 0, hold: 0 });
    }
    const s = sessions.get(session.id);
    s.volume += loadVolumeE7(set);
    s.sets += 1;
    s.reps += set.reps;
    s.hold += set.durationSeconds ?? 0;
  }

  const byWeek = new Map();
  for (let w = rangeStart; w <= currentWeek; w += 7) byWeek.set(w, { workouts: 0, volume: 0, sets: 0, reps: 0, hold: 0 });
  for (const s of sessions.values()) {
    const week = byWeek.get(mondayOf(s.day));
    if (!week) continue;
    week.workouts += 1;
    week.volume += s.volume;
    week.sets += s.sets;
    week.reps += s.reps;
    week.hold += s.hold;
  }

  // WeeklyStreak#consecutiveWeeks: the current week counts once trained, but an untrained one so
  // far does not break the streak.
  const trained = (w) => (byWeek.get(w)?.workouts ?? 0) > 0;
  let cursor = trained(currentWeek) ? currentWeek : currentWeek - 7;
  let streak = 0;
  while (cursor >= rangeStart && trained(cursor)) {
    streak += 1;
    cursor -= 7;
  }

  let thisMonth = 0;
  let lastMonth = 0;
  const days = new Map();
  for (const s of sessions.values()) {
    if (s.day >= today - 29 && s.day <= today) thisMonth += s.volume;
    else if (s.day >= today - 59 && s.day <= today - 30) lastMonth += s.volume;
    if (s.day >= today - (HEATMAP_DAYS - 1) && s.day <= today) {
      const d = days.get(s.day) ?? { sessionCount: 0, setCount: 0 };
      d.sessionCount += 1;
      d.setCount += s.sets;
      days.set(s.day, d);
    }
  }

  return {
    weeks: [...byWeek].map(([w, v]) => ({
      weekStart: isoDay(w),
      workoutCount: v.workouts,
      totalVolumeLb: tenths(v.volume, E7),
      totalSets: v.sets,
      totalReps: v.reps,
      totalHoldSeconds: v.hold,
    })),
    currentStreakWeeks: streak,
    workoutsThisWeek: byWeek.get(currentWeek)?.workouts ?? 0,
    workoutsLastWeek: byWeek.get(currentWeek - 7)?.workouts ?? 0,
    volumeThisMonthLb: tenths(thisMonth, E7),
    volumeLastMonthLb: tenths(lastMonth, E7),
    workoutDays: [...days].sort((a, b) => a[0] - b[0]).map(([day, d]) => ({ date: isoDay(day), ...d })),
    hasAnyHistory: sessions.size > 0 || hiddenSessions > 0,
  };
}

// ── one exercise over time: GET /trends/exercises/{id} ────────────────────────────────────────

// `windowStart` is the History window's floor (null on Plus). The range is clamped to it rather than
// the sets filtered, as the server does -- but the device holds nothing behind it, so on Free a
// dot can be marked a record against the window rather than the person's all-time best. Accepted
// (docs/architecture/prs-trends-from-history.md, "Decisions"): the same gap History's badges have.
export function exerciseTrend(history, exerciseId, { weeks, zone, now, windowStart = null }) {
  const effectiveWeeks = Math.min(Math.max(weeks, 1), MAX_WEEKS);
  let rangeStart = mondayOf(localDay(now, zone)) - 7 * (effectiveWeeks - 1);
  if (windowStart) rangeStart = Math.max(rangeStart, localDay(windowStart, zone));

  const items = setsInOrder(history, exerciseId);
  const kind = volumeKindOf(items.map(({ set }) => set));
  let runningBest = 0;
  const inWindow = new Map();
  for (const item of items) {
    const day = localDay(item.session.startedAt, zone);
    if (day < rangeStart) {
      runningBest = Math.max(runningBest, comparableValue(item.set));
    } else {
      if (!inWindow.has(item.session.id)) inWindow.set(item.session.id, { day, items: [] });
      inWindow.get(item.session.id).items.push(item);
    }
  }

  const points = [];
  for (const [sessionId, { day, items: sessionItems }] of inWindow) {
    const best = bestSet(sessionItems);
    const bestValue = comparableValue(best.set);
    const isPr = bestValue > runningBest;
    if (isPr) runningBest = bestValue;

    let heaviest = null;
    let heaviestReps = 0;
    let bestSetVolume = 0;
    let volume = 0;
    let totalReps = 0;
    let bestHold = null;
    let totalHold = 0;
    for (const { set } of sessionItems) {
      if (isHold(set)) {
        totalHold += set.durationSeconds;
        if (bestHold == null || set.durationSeconds > bestHold) bestHold = set.durationSeconds;
      }
      const lb = weightLbE7(set);
      if (heaviest == null || lb > heaviest || (lb === heaviest && set.reps > heaviestReps)) {
        heaviest = lb;
        heaviestReps = set.reps;
      }
      bestSetVolume = Math.max(bestSetVolume, loadVolumeE7(set));
      volume += setVolumeScaled(set, kind);
      totalReps += set.reps;
    }

    points.push({
      date: isoDay(day),
      sessionId,
      weightLb: tenths(weightLbE7(best.set), E7),
      reps: best.set.reps,
      est1rmLb: tenths(toE7(bestValue), E7),
      isPr,
      heaviestWeightLb: tenths(heaviest, E7),
      heaviestWeightReps: heaviestReps,
      bestSetVolumeLb: tenths(bestSetVolume, E7),
      sessionVolume: tenths(volume, volumeScale(kind)),
      volumeKind: kind,
      totalReps,
      setCount: sessionItems.length,
      bestHoldSeconds: bestHold,
      totalHoldSeconds: totalHold,
    });
  }
  return points;
}

// ── one exercise's all-time records: GET /exercises/{id}/records ──────────────────────────────

const recordEntry = (valueScaled, scale, { set, session }, zone) => ({
  valueLb: tenths(valueScaled, scale),
  weightLb: tenths(weightLbE7(set), E7),
  reps: set.reps,
  durationSeconds: set.durationSeconds ?? null,
  date: isoDay(localDay(session.startedAt, zone)),
});

export function exerciseRecords(history, exerciseId, { zone }) {
  const items = setsInOrder(history, exerciseId);
  if (items.length === 0) {
    return {
      bestEst1rm: null, heaviestWeight: null, bestSetVolume: null, bestSessionVolume: null, mostReps: null,
      longestHold: null, heaviestLoadHeld: null, totalSets: 0, totalReps: 0, totalHoldSeconds: 0,
      totalVolumeLb: 0, bodyweightOnly: false, durationTracked: false, volumeKind: null,
    };
  }
  const durationTracked = items.some(({ set }) => isHold(set));
  const kind = volumeKindOf(items.map(({ set }) => set));
  let heaviest = null;
  let bestEst1rm = null;
  let bestEst1rmLb = null;
  let bestSetVolume = null;
  let mostReps = null;
  let longestHold = null;
  let heaviestLoadHeld = null;
  let totalReps = 0;
  let totalHold = 0;
  let totalVolume = 0;
  let bodyweightOnly = true;
  const volume = new Map();

  for (const item of items) {
    const { set, session } = item;
    const lb = weightLbE7(set);
    if (heaviest == null || isBetter(lb, set.reps, weightLbE7(heaviest.set), heaviest.set.reps)) heaviest = item;
    // Bodyweight sets are skipped rather than ranked by reps: a rep count would outrank pounds.
    if (Number(set.weight) !== 0) {
      const est = toE7(comparableLb(set.weight, set.reps, set.unit));
      if (bestEst1rm == null || isBetter(est, lb, bestEst1rmLb, weightLbE7(bestEst1rm.set))) {
        bestEst1rm = item;
        bestEst1rmLb = est;
      }
    }
    if (bestSetVolume == null || isBetter(loadVolumeE7(set), lb, loadVolumeE7(bestSetVolume.set), weightLbE7(bestSetVolume.set))) {
      bestSetVolume = item;
    }
    if (mostReps == null || isBetter(set.reps, lb, mostReps.set.reps, weightLbE7(mostReps.set))) mostReps = item;
    if (isHold(set)) {
      totalHold += set.durationSeconds;
      if (longestHold == null || isBetter(set.durationSeconds, lb, longestHold.set.durationSeconds, weightLbE7(longestHold.set))) longestHold = item;
      if (heaviestLoadHeld == null || isBetter(lb, set.durationSeconds, weightLbE7(heaviestLoadHeld.set), heaviestLoadHeld.set.durationSeconds)) heaviestLoadHeld = item;
    }
    totalReps += set.reps;
    totalVolume += loadVolumeE7(set);
    if (Number(set.weight) !== 0) bodyweightOnly = false;
    if (!volume.has(session.id)) volume.set(session.id, { session, total: 0 });
    volume.get(session.id).total += setVolumeScaled(set, kind);
  }

  let bestSession = null;
  for (const s of volume.values()) if (bestSession == null || s.total > bestSession.total) bestSession = s;

  return {
    bestEst1rm: bestEst1rm == null || durationTracked ? null : recordEntry(bestEst1rmLb, E7, bestEst1rm, zone),
    heaviestWeight: recordEntry(weightLbE7(heaviest.set), E7, heaviest, zone),
    bestSetVolume: recordEntry(loadVolumeE7(bestSetVolume.set), E7, bestSetVolume, zone),
    bestSessionVolume: {
      valueLb: tenths(bestSession.total, volumeScale(kind)),
      weightLb: null,
      reps: null,
      durationSeconds: null,
      date: isoDay(localDay(bestSession.session.startedAt, zone)),
    },
    mostReps: durationTracked ? null : recordEntry(mostReps.set.reps, 1, mostReps, zone),
    longestHold: longestHold == null ? null : recordEntry(longestHold.set.durationSeconds, 1, longestHold, zone),
    heaviestLoadHeld: heaviestLoadHeld == null ? null : recordEntry(weightLbE7(heaviestLoadHeld.set), E7, heaviestLoadHeld, zone),
    totalSets: items.length,
    totalReps,
    totalHoldSeconds: totalHold,
    totalVolumeLb: tenths(totalVolume, E7),
    bodyweightOnly,
    durationTracked,
    volumeKind: kind,
  };
}
